version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10

    steps:
      - checkout

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      # Fragmento de código para desplegar en PythonAnywhere
      - name: Deploy to PythonAnywhere
        run: |
          [vicevil77]
          -[ https://github.com/vicevil77/taller_despliegue.git]
          curl -X POST https://api.github.com/repos/[vicevil_77]/[ https://github.com/vicevil77/taller_despliegue.git]/commits/[commit-hash]/status?token=[tu-token-de-acceso-personal] -d '{
            "state": "success",
            "description": "Aplicación desplegada correctamente en PythonAnywhere",
            "target_url": "https://vicevil.pythonanywhere.com/"
          }'
  